# This is the default Travis setup provided in the docs.
# TODO: It may be necessary to change tooling versions!

language: android
# dist: trusty
jdk:
  - openjdk15
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - tools
    - platform-tools

    # The BuildTools version used by your project
    - build-tools-30.0.3

    # The SDK version used to compile your project
    - android-30

    # Additional components
    # - extra-google-google_play_services
    # - extra-google-m2repository
    # - extra-android-m2repository

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    # - sys-img-x86-android-26
    # - sys-img-armeabi-v7a-android-17
    
addons:
  sonarcloud:
    organization: castanie # the key of the org you chose at step #3
    token: ${SONAR_TOKEN} # encrypted value of your token
script:
  # other script steps might be done before running the actual analysis
  - sonar-scanner
