language: android

jdk:
  - openjdk11

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - tools
    - platform-tools

    # The BuildTools version used by your project
    - build-tools-30.0.3

    # The SDK version used to compile your project
    - android-30

    # Additional components
    # - extra-google-google_play_services
    # - extra-google-m2repository
    # - extra-android-m2repository

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    # - sys-img-x86-android-26
    # - sys-img-armeabi-v7a-android-17

addons:
  sonarcloud:
    organization: raphilesacher # the key of the org you chose
    token: ${SONAR_TOKEN} # encrypted value of your token

before_install:
  - jdk_switcher use openjdk8
  - yes | sdkmanager "platforms;android-30"
  - export JAVA_HOME=$HOME/openjdk11

before_script:
  - chmod +x gradlew

script:
  - ./gradlew clean
  - ./gradlew :core:jacocoTestReport
  - ./gradlew :server:jacocoTestReport
  - ./gradlew sonarqube

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache